default:
  tags:
    - kantor

stages:
  - preparation
  - test
  - build
  - deploy

composer:
  stage: preparation
  script:
    - composer update --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - composer dump-autoload
  artifacts:
    paths:
      - vendor/
    expire_in: 1 days
    when: always
  cache:
    paths:
      - vendor/
    key:
      files:
        - composer.lock

sonarqube-check:
  stage: test
  dependencies:
    - composer  
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.login=$SONAR_TOKEN
  allow_failure: true
  only:
    - master

docker:
  stage: build
  before_script:
    - echo "$CUSTOM_REGISTRY_PASSWORD" | docker login -u "$CUSTOM_REGISTRY_USER" --password-stdin $CUSTOM_REGISTRY_URL
  script:
    - export IMAGE=$CUSTOM_REGISTRY_BASEDN/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
    - docker build -t $IMAGE .
    - docker push $IMAGE

kubernetes:
  stage: deploy
  only:
    - master
  script:
    - echo "$KUBECONFIG_TORCHE_COM" > kube_torche.config
    - export KUBECONFIG=kube_torche.config
    - sed -i "s,<IMAGE_NAME>,${CUSTOM_REGISTRY_BASEDN}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME},g" .kubernetes/deploy.yaml
    - sed -i "s,<IMAGE_VERSION>,${CI_COMMIT_SHORT_SHA},g" .kubernetes/deploy.yaml
    - sed -i "s,<PROJECT_NAME>,${CI_PROJECT_NAME},g" .kubernetes/deploy.yaml
    - sed -i "s,<PROJECT_NAMESPACE>,${CI_PROJECT_NAMESPACE},g" .kubernetes/deploy.yaml
    - sed -i "s,<PROJECT_NAME>,${CI_PROJECT_NAME},g" .kubernetes/config.yaml
    - sed -i "s,<PROJECT_NAMESPACE>,${CI_PROJECT_NAMESPACE},g" .kubernetes/config.yaml
    - kubectl apply -f .kubernetes/config.yaml
    - kubectl apply -f .kubernetes/deploy.yaml
    - echo "Application should be accessible at http://${CI_PROJECT_NAME}-${CI_PROJECT_NAMESPACE}.devel.torche-indonesia.com/"
